### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by koldunovn** [bird-house/emu#1]
Hi,

I am trying to build docker image for `emu`. At some point I get this:
```
Installing Anaconda ...
mkdir: cannot create directory '//anaconda': Permission denied
ERROR: Could not create directory: //anaconda
make: *** [anaconda] Error 1
```
I am not sure if this is problem in the Dockerfile, or something wrong with my docker installation.

**Comment by cehbrecht** [comment]
There is already a docker image available:

https://registry.hub.docker.com/u/birdhouse/emu/

The Dockerfile is generated. Haven't seen this error message. Need to check it.

**Comment by koldunovn** [comment]
The prebuild docker image worked, thanks!
