### ISSUE TITLE
Configure issue and PR templates in this github repo

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/emu#15]
see:
https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by huard** [comment]
Good idea !

**Comment by tomLandry** [comment]
I'd tag this PAVICS too, meaning we should adopt and normalize this.

**Comment by cehbrecht** [comment]
I have modified the one in the cookiecutter-birdhouse:
https://github.com/bird-house/cookiecutter-birdhouse/blob/pingudev/.github/ISSUE_TEMPLATE.md

It is a mixture of the original cookiecutter template and the one from pywps:
* https://github.com/audreyr/cookiecutter-pypackage/blob/master/.github/ISSUE_TEMPLATE.md
* https://github.com/geopython/pywps/tree/develop/.github

**Comment by huard** [comment]
Looks good.

**Comment by cehbrecht** [comment]
Added templates and leave this ticket open to let them grow :)

A `CONTRIBUTING.md` can also be added.

**Comment by cehbrecht** [comment]
done.
