### ISSUE TITLE
fix readthedocs build

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/emu#16]
... it was using `requirements/rtd.txt`.

**Comment by huard** [comment]
Using the autoprocess directive makes building the docs on rtd more complicated, as we need to install the package dependencies.

**Comment by cehbrecht** [comment]
Currently I can't get this to work on ReadTheDocs. It is possible to setup a virtualenv on ReadTheDocs but I don't have the latest pywps on pypi. It will also fail if we include more then pure Python dependencies. 

@huard Is it possible to make the pywps sphinx extension like the [sphinx autoapi](https://sphinx-autoapi.readthedocs.io/en/latest/)? `autoapi` is using a static code parser and does not need "Python imports", dependencies.

**Comment by huard** [comment]
Well, I have no idea how static code parsers work. If it's just scraping the docstring, then no, it's not possible. If there is a fancy mechanism that understands subclasses, attributes, then yes, it might be possible. 

Also, there does not seem to be any hooks within the autoapi extension to write domain specific parsers, so we're talking about first making change to autoapi itself, then writing our own parser on top of it. 

Are you sure about the pure python dependencies ? If we require numpy, surely it can install it through pip. 

Can we fix this by clearly separating import dependencies and run dependencies (as in ansible)?

Travis is able to import the code, could we get it to also build the docs and push them to githubio ?

**Comment by cehbrecht** [comment]
@huard I got it working with having a separate `rtd.txt` environment for readthedocs. It pulls pywps from github:
https://emu.readthedocs.io/en/latest/processes.html

I have moved the discussion to pywps: 
https://github.com/geopython/pywps/issues/343
