### ISSUE TITLE
PercentCompleted

### ISSUE THREAD

**Issue by huard** [bird-house/emu#62]
## Description

Processes should provide the percent completed information so we can log their progress.

**Comment by cehbrecht** [comment]
... technically this is already there. It is only "visible" for long running processes ... like for the `sleep` process.

**Comment by huard** [comment]
Well, in practice if you call "hello" and then ask for the percentCompleted, it returns 0.

**Comment by cehbrecht** [comment]
right ... I experienced this with trying the progess-bar widget. But we could set in pywps progress to 100 percent when the job has finished successfully. So we don't need to remember in our processes to set this value.
