### ISSUE TITLE
Add makefile recipe for testing Jupyter Notebooks

### ISSUE THREAD

**Issue by Zeitsperre** [bird-house/emu#92]
In a few other birds, I've added a recipe for running tests on Jupyter Notebooks. This allows for users to evaluate whether the output of their notebooks is consistent on their environment.

This requires a few more libraries (jupyter, nbval) that could be added to the environment.yml or their requirements.txt (ideally, this would be installed via Anaconda). I would also add an example notebook that attempts to load emu as a smoke test.

**Comment by cehbrecht** [comment]
I suppose the notebook tests are optional ... so we don't need to add the requirements to the default `environment.yml` but may have an extra folder/environment like in birdy?
https://github.com/bird-house/birdy/tree/master/notebooks

**Comment by Zeitsperre** [comment]
I didn't realize that Birdy already had a few examples. I can borrow a bit of code from that to address this issue. The goal would be to streamline the testing of notebooks in the makefile so that users can easily run tests themselves. For the requirements, these would strictly be for development purposes so placing them somewhere away from base requirements makes sense.

We could also consider adding a few notebooks that could be integrated directly into the docs build, but that might be worth opening as a separate issue (see: https://pavics-raven.readthedocs.io/en/latest/notebooks/index.html).
