### ISSUE TITLE
DAP server running in parallel with Emu

### ISSUE THREAD

**Issue by huard** [bird-house/emu#98]
## Description

We have a lot of processes that return netCDF files. As of now, they are served as file URL. It would be useful to be able to serve them as well through DAP. 

I suggest Emu includes an option to configure and launch a netCDF handler based on pydap to serve the outputs created by Emu. In production, we would use THREDDS, but I think it would be easier for testing to use pydap. 

See https://github.com/geopython/pywps/pull/513

**Comment by huard** [comment]
@cehbrecht Would that be useful for you ?

**Comment by nilshempelmann** [comment]
Thats a good Idea and would enable processing options like bbox over entire datasets. 
But I remember we had serious problems running dap options some years ago.

**Comment by cehbrecht** [comment]
@huard you mean that we deploy pydap with emu and start it optionally?

**Comment by huard** [comment]
Yes, if it doesn't add too much complexity. I'm concerned about the state of pydap however. It doesn't seem to be actively maintained.

**Comment by cehbrecht** [comment]
@huard ... we can give it a try to add the pydap service.

**Comment by tlvu** [comment]
@cehbrecht 

> you mean that we deploy pydap with emu and start it optionally?

Would optionally starting a Thredds docker image along side with emu be a good alternative to pydap for testing?

**Comment by cehbrecht** [comment]
> @cehbrecht
> 
> > you mean that we deploy pydap with emu and start it optionally?
> 
> Would optionally starting a Thredds docker image along side with emu be a good alternative to pydap for testing?

... we could make it available as a docker container demo (both wps and thredds are started as container). Then we don't need to change the emu code.

**Comment by jameshiebert** [comment]
I'm interested to know what you mean by "testing". We have numerous projects that spin up a PyDAP DAP server as part of their automated unit and integration tests, and it's not a big deal. Is that what you have in mind here?

Some considerations:

1. The PyDAP stack has a long list of requirements, that you would need to add to your test requirements which could add a substantial amount of complexity to your testing regime. Are you comfortable with that?
2. I'm not intimately familiar with the THREDDS implementation of DAP. Both THREDDS and PyDAP *should* follow the spec, but in practice that's not always the case. Introducing a different DAP server than what you intend to use in production has the potential to complicate things a lot, if you're not actually testing your production software. Basically you're proposing to [mock out](https://en.wikipedia.org/wiki/Mock_object) THREDDS with PyDAP. Of course, there are often cases where mocking is perfectly fine and recommended, but are you sure this is one of them?

**Comment by huard** [comment]
Exactly. I want to test that processes returning a DAP link instead of a fileServer link work as expected. 

1. Could go in requirements_dev, but did not think about it too much so far. 
2. Good point. Probably safer to test with THREDDS then, as Long proposes.
